language: php
php:
  - '7.0'
  - '7.1'
  - '7.2'
  - '7.3'
install:
  - composer install --dev --no-interaction
script:
  - composer test
after_success:
 - travis_retry php vendor/bin/php-coveralls -v
